In [1]:
#Q1.1: Create a 4x4 identity matrix using np.eye()
import numpy as np
s=np.eye(4)
s

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
# Q1.2: Create an array of 8 zeros using np.zeros()
a= np.zeros(8)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# Q1.3: Create an array of 6 ones using np.ones()
a=np.ones(6)
a

array([1., 1., 1., 1., 1., 1.])

In [5]:
# Q1.4: Create an array with values from 0 to 15 using np.arange()
array = np.arange(0,16)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [6]:
# Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()
a=np.linspace(0,100,8)
print(a)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


In [7]:
# Question 2: Array Attributes and Information

In [2]:
#Q2.1: What is the shape of the banking_data array?
# Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active
bd=np.array([
    [1, 26000, 310, 1200, 10],
    [2, 33000, 460, 1500, 15],
    [3, 23000, 350, 1100, 8],
    [4, 48000, 520, 1600, 20],
    [5, 24000, 430, 1400, 12],
    [6, 28000, 340, 1300, 9],
    [7, 33000, 470, 1700, 18],
    [8, 37000, 430, 1250, 14],
    [9, 45000, 560, 1800, 25],
    [10, 31000, 430, 1450, 11]
])
print(bd)

[[    1 26000   310  1200    10]
 [    2 33000   460  1500    15]
 [    3 23000   350  1100     8]
 [    4 48000   520  1600    20]
 [    5 24000   430  1400    12]
 [    6 28000   340  1300     9]
 [    7 33000   470  1700    18]
 [    8 37000   430  1250    14]
 [    9 45000   560  1800    25]
 [   10 31000   430  1450    11]]


In [12]:
bd.shape

(10, 5)

In [13]:
#Q2.2: What is the data type of the banking_data array?
bd.dtype

dtype('int64')

In [14]:
#Q2.3: What is the size (total number of elements) of the banking_data array?
bd.size

50

In [15]:
#Q2.4: What is the number of dimensions of the banking_data array?
bd.ndim

2

In [17]:
#Q2.5: What is the memory size of the banking_data array in bytes?
bd.nbytes

400

Q 3:Indexing and slicing


In [21]:
#Q3.1: Extract the first row of banking_data
bd[0]

array([    1, 26000,   310,  1200,    10])

In [19]:
#Q3.2: Extract the last row of banking_data
bd[-1]

array([   10, 31000,   430,  1450,    11])

In [29]:
#Q3.3: Extract the Account_Balance column (column index 1)
bd[:,1]

array([26000, 33000, 23000, 48000, 24000, 28000, 33000, 37000, 45000,
       31000])

In [30]:
#Q3.4: Extract the first 4 rows and first 3 columns
bd[:4,:3]

array([[    1, 26000,   310],
       [    2, 33000,   460],
       [    3, 23000,   350],
       [    4, 48000,   520]])

In [31]:
#Q3.5: Extract rows 3 to 7 (inclusive)
bd[3:8]

array([[    4, 48000,   520,  1600,    20],
       [    5, 24000,   430,  1400,    12],
       [    6, 28000,   340,  1300,     9],
       [    7, 33000,   470,  1700,    18],
       [    8, 37000,   430,  1250,    14]])


Question 4: Mathematical Operations

In [32]:
#Q4.1: Calculate the sum of all account balances
bd

array([[    1, 26000,   310,  1200,    10],
       [    2, 33000,   460,  1500,    15],
       [    3, 23000,   350,  1100,     8],
       [    4, 48000,   520,  1600,    20],
       [    5, 24000,   430,  1400,    12],
       [    6, 28000,   340,  1300,     9],
       [    7, 33000,   470,  1700,    18],
       [    8, 37000,   430,  1250,    14],
       [    9, 45000,   560,  1800,    25],
       [   10, 31000,   430,  1450,    11]])

In [33]:
bd[:,1].sum()

np.int64(328000)

In [34]:
#Q4.2: Calculate the mean account balance
bd[:,1].mean()

np.float64(32800.0)

In [35]:
#Q4.3: Calculate the standard deviation of account balances
bd[:,1].std()

np.float64(8022.468448052632)

In [36]:
#Q4.4: Calculate the variance of account balances
bd[:,1].var()

np.float64(64360000.0)

In [39]:
#Q4.5: Calculate the median account balance
s=bd[:,1]
t=np.median(s)
t

np.float64(32000.0)


Question 5: Statistical Functions

In [44]:
bd

array([[    1, 26000,   310,  1200,    10],
       [    2, 33000,   460,  1500,    15],
       [    3, 23000,   350,  1100,     8],
       [    4, 48000,   520,  1600,    20],
       [    5, 24000,   430,  1400,    12],
       [    6, 28000,   340,  1300,     9],
       [    7, 33000,   470,  1700,    18],
       [    8, 37000,   430,  1250,    14],
       [    9, 45000,   560,  1800,    25],
       [   10, 31000,   430,  1450,    11]])

In [42]:
#Q5.1: Find the minimum and maximum account balances
a=bd[:,1]
print(a.min())
print(a.max())

23000
48000


In [43]:
#Q5.2: Find the minimum and maximum credit scores
a=bd[:,2]
print(a.min())
print(a.max())

310
560


In [45]:
#Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)
s=np.percentile(bd[:,1],[25,50,75])
print(s)

[26500. 32000. 36000.]


In [46]:
#Q5.4: Calculate the correlation between account balance and credit score
a=bd[:,1]
c=bd[:,2]
np.corrcoef(a,c)

array([[1.        , 0.82989364],
       [0.82989364, 1.        ]])

In [47]:
#Q5.5: Calculate the covariance between account balance and credit score
a=bd[:,1]
c=bd[:,2]
np.cov(a,c)

array([[7.15111111e+07, 5.55555556e+05],
       [5.55555556e+05, 6.26666667e+03]])


Array Reshaping and Manipulation


In [48]:
#Q6.1: Reshape the banking_data to 5 rows × 10 columns
bd

array([[    1, 26000,   310,  1200,    10],
       [    2, 33000,   460,  1500,    15],
       [    3, 23000,   350,  1100,     8],
       [    4, 48000,   520,  1600,    20],
       [    5, 24000,   430,  1400,    12],
       [    6, 28000,   340,  1300,     9],
       [    7, 33000,   470,  1700,    18],
       [    8, 37000,   430,  1250,    14],
       [    9, 45000,   560,  1800,    25],
       [   10, 31000,   430,  1450,    11]])

In [49]:
s=bd.reshape(5,10)
s

array([[    1, 26000,   310,  1200,    10,     2, 33000,   460,  1500,
           15],
       [    3, 23000,   350,  1100,     8,     4, 48000,   520,  1600,
           20],
       [    5, 24000,   430,  1400,    12,     6, 28000,   340,  1300,
            9],
       [    7, 33000,   470,  1700,    18,     8, 37000,   430,  1250,
           14],
       [    9, 45000,   560,  1800,    25,    10, 31000,   430,  1450,
           11]])

In [50]:
#Q6.2: Flatten the banking_data to a 1D array
bd.flatten()

array([    1, 26000,   310,  1200,    10,     2, 33000,   460,  1500,
          15,     3, 23000,   350,  1100,     8,     4, 48000,   520,
        1600,    20,     5, 24000,   430,  1400,    12,     6, 28000,
         340,  1300,     9,     7, 33000,   470,  1700,    18,     8,
       37000,   430,  1250,    14,     9, 45000,   560,  1800,    25,
          10, 31000,   430,  1450,    11])

In [53]:
#Q6.3:Transpose the banking_data
bd.T

array([[    1,     2,     3,     4,     5,     6,     7,     8,     9,
           10],
       [26000, 33000, 23000, 48000, 24000, 28000, 33000, 37000, 45000,
        31000],
       [  310,   460,   350,   520,   430,   340,   470,   430,   560,
          430],
       [ 1200,  1500,  1100,  1600,  1400,  1300,  1700,  1250,  1800,
         1450],
       [   10,    15,     8,    20,    12,     9,    18,    14,    25,
           11]])

In [57]:
#Q6.4: Split the banking_data into 2 equal parts vertically
np.vsplit(bd,2)

[array([[    1, 26000,   310,  1200,    10],
        [    2, 33000,   460,  1500,    15],
        [    3, 23000,   350,  1100,     8],
        [    4, 48000,   520,  1600,    20],
        [    5, 24000,   430,  1400,    12]]),
 array([[    6, 28000,   340,  1300,     9],
        [    7, 33000,   470,  1700,    18],
        [    8, 37000,   430,  1250,    14],
        [    9, 45000,   560,  1800,    25],
        [   10, 31000,   430,  1450,    11]])]

In [61]:
#Q6.5: Split the banking_data into 2 equal parts horizontally
bd

array([[    1, 26000,   310,  1200,    10],
       [    2, 33000,   460,  1500,    15],
       [    3, 23000,   350,  1100,     8],
       [    4, 48000,   520,  1600,    20],
       [    5, 24000,   430,  1400,    12],
       [    6, 28000,   340,  1300,     9],
       [    7, 33000,   470,  1700,    18],
       [    8, 37000,   430,  1250,    14],
       [    9, 45000,   560,  1800,    25],
       [   10, 31000,   430,  1450,    11]])

In [63]:
bd=np.array([[    1, 26000,   310,  1200,    10],
       [    2, 33000,   460,  1500,    15],
       [    3, 23000,   350,  1100,     8],
       [    4, 48000,   520,  1600,    20],
       [    5, 24000,   430,  1400,    12],
       [    6, 28000,   340,  1300,     9],
       [    7, 33000,   470,  1700,    18],
       [    8, 37000,   430,  1250,    14],
       [    9, 45000,   560,  1800,    25],
       [   10, 31000,   430,  1450,    11]])
np.hsplit(bd,2)

ValueError: array split does not result in an equal division


Question 7: Logical Operations and Filtering

In [19]:
#Q7.1: Find customers with account balance greater than $10
s=bd[bd[:,1]>9000]
t=s[:,0]
t

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
#Q7.2: Find customers with credit score greater than 800
s=bd[bd[:,2]>800]
t=s[:,0]
t

array([], dtype=int64)

In [23]:
#Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750
s=bd[(bd[:, 3] > 50) & (bd[:, 2] < 750)]
t=s[:,0]
t

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
#Q7.4: Count how many customers have account balance between $10,000 and $100,000
np.sum((bd[:,1]>=10000) & (bd[:,1]<=100000))

np.int64(10)

In [75]:
#Q7.5: Find the index of the customer with the highest credit score
np.argmax(bd[:, 2])

np.int64(8)

Sorting and Searching

In [6]:
#Q8.1: Sort the banking_data by account balance (ascending)
s=bd[bd[:,1].argsort()]
s

array([[    3, 23000,   350,  1100,     8],
       [    5, 24000,   430,  1400,    12],
       [    1, 26000,   310,  1200,    10],
       [    6, 28000,   340,  1300,     9],
       [   10, 31000,   430,  1450,    11],
       [    7, 33000,   470,  1700,    18],
       [    2, 33000,   460,  1500,    15],
       [    8, 37000,   430,  1250,    14],
       [    9, 45000,   560,  1800,    25],
       [    4, 48000,   520,  1600,    20]])

In [7]:
#Q8.2: Sort the banking_data by credit score (descending)
s=bd[bd[:,2].argsort()[::-1]]
s

array([[    9, 45000,   560,  1800,    25],
       [    4, 48000,   520,  1600,    20],
       [    7, 33000,   470,  1700,    18],
       [    2, 33000,   460,  1500,    15],
       [   10, 31000,   430,  1450,    11],
       [    8, 37000,   430,  1250,    14],
       [    5, 24000,   430,  1400,    12],
       [    3, 23000,   350,  1100,     8],
       [    6, 28000,   340,  1300,     9],
       [    1, 26000,   310,  1200,    10]])

In [8]:
#Q8.3: Find the indices that would sort the array by years active
s=np.argsort(bd[:,4])
s

array([2, 5, 0, 9, 4, 7, 1, 6, 3, 8])

In [9]:
bd

array([[    1, 26000,   310,  1200,    10],
       [    2, 33000,   460,  1500,    15],
       [    3, 23000,   350,  1100,     8],
       [    4, 48000,   520,  1600,    20],
       [    5, 24000,   430,  1400,    12],
       [    6, 28000,   340,  1300,     9],
       [    7, 33000,   470,  1700,    18],
       [    8, 37000,   430,  1250,    14],
       [    9, 45000,   560,  1800,    25],
       [   10, 31000,   430,  1450,    11]])

In [15]:
#Q8.4: Find the customer with the second highest account balance
s=np.argsort(bd[:,1])
t=s[-2]
t

np.int64(8)

In [16]:
#Q8.5: Find the customer with the lowest transaction count
s=np.argsort(bd[:,3])
t=s[0]
t

np.int64(2)

Question 9: Mathematical Functions

In [26]:
#Q9.1: Calculate the absolute values of all elements
np.abs(bd)

array([[    1, 26000,   310,  1200,    10],
       [    2, 33000,   460,  1500,    15],
       [    3, 23000,   350,  1100,     8],
       [    4, 48000,   520,  1600,    20],
       [    5, 24000,   430,  1400,    12],
       [    6, 28000,   340,  1300,     9],
       [    7, 33000,   470,  1700,    18],
       [    8, 37000,   430,  1250,    14],
       [    9, 45000,   560,  1800,    25],
       [   10, 31000,   430,  1450,    11]])

In [27]:
#Q9.2: Calculate the square root of all account balances
np.sqrt(bd[:,1])

array([161.24515497, 181.65902125, 151.65750888, 219.089023  ,
       154.91933385, 167.33200531, 181.65902125, 192.35384062,
       212.13203436, 176.06816862])

In [30]:
#Q9.3: Calculate the square of all credit scores
np.square(bd[:,2])

array([ 96100, 211600, 122500, 270400, 184900, 115600, 220900, 184900,
       313600, 184900])

In [31]:
bd

array([[    1, 26000,   310,  1200,    10],
       [    2, 33000,   460,  1500,    15],
       [    3, 23000,   350,  1100,     8],
       [    4, 48000,   520,  1600,    20],
       [    5, 24000,   430,  1400,    12],
       [    6, 28000,   340,  1300,     9],
       [    7, 33000,   470,  1700,    18],
       [    8, 37000,   430,  1250,    14],
       [    9, 45000,   560,  1800,    25],
       [   10, 31000,   430,  1450,    11]])

In [34]:
#Q9.4: Calculate the exponential of all transaction counts
import numpy as np
bd=np.array([[    1, 26000,   310,  1200,    10],
       [    2, 33000,   460,  1500,    15],
       [    3, 23000,   350,  1100,     8],
       [    4, 48000,   520,  1600,    20],
       [    5, 24000,   430,  1400,    12],
       [    6, 28000,   340,  1300,     9],
       [    7, 33000,   470,  1700,    18],
       [    8, 37000,   430,  1250,    14],
       [    9, 45000,   560,  1800,    25],
       [   10, 31000,   430,  1450,    11]])
np.exp(bd[:,3])

C:\Users\afrid\AppData\Local\Temp\ipykernel_33284\2602111107.py:13: RuntimeWarning: overflow encountered in exp
  np.exp(bd[:,3])


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [35]:
#Q9.5: Calculate the natural logarithm of all account balances
np.log(bd[:,1])

array([10.16585182, 10.40426284, 10.04324949, 10.77895629, 10.08580911,
       10.23995979, 10.40426284, 10.51867319, 10.71441777, 10.34174248])

Advanced Operations

In [36]:
 #Q10.1: Calculate the cumulative sum of account balances
np.cumsum(bd[:,1])

array([ 26000,  59000,  82000, 130000, 154000, 182000, 215000, 252000,
       297000, 328000])

In [37]:
#Q10.2: Calculate the cumulative product of transaction counts
np.cumprod(bd[:,3])

array([                1200,              1800000,           1980000000,
              3168000000000,     4435200000000000,  5765760000000000000,
        6570896860228091904,  4819962484364410880,  5962757212450324480,
       -5525012516809211904])

In [38]:
#Q10.3: Calculate the difference between consecutive account balances
np.diff(bd[:,1])

array([  7000, -10000,  25000, -24000,   4000,   5000,   4000,   8000,
       -14000])

In [39]:
#Q10.4: Calculate the gradient of account balances
np.gradient(bd[:,1])

array([  7000.,  -1500.,   7500.,    500., -10000.,   4500.,   4500.,
         6000.,  -3000., -14000.])

In [40]:
#Q10.5: Calculate the histogram of account balances with 5 bins
np.histogram(bd[:,1],bins=5)

(array([3, 2, 3, 0, 2]),
 array([23000., 28000., 33000., 38000., 43000., 48000.]))

In [53]:
bd

array([[    1, 26000,   310,  1200,    10],
       [    2, 33000,   460,  1500,    15],
       [    3, 23000,   350,  1100,     8],
       [    4, 48000,   520,  1600,    20],
       [    5, 24000,   430,  1400,    12],
       [    6, 28000,   340,  1300,     9],
       [    7, 33000,   470,  1700,    18],
       [    8, 37000,   430,  1250,    14],
       [    9, 45000,   560,  1800,    25],
       [   10, 31000,   430,  1450,    11]])

Random Numbers and Simulation

In [43]:
#Q11.1: Generate 6 random integers between 1 and 1000
s=np.random.randint(1,1000,6)
s

array([566, 291, 691, 894, 397, 458], dtype=int32)

In [44]:
#Q11.2: Generate 6 random floats between 0 and 1
np.random.rand(6)

array([0.08724073, 0.44310907, 0.32305193, 0.9759566 , 0.04561227,
       0.53394441])

In [45]:
# Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)
np.random.normal(700,100,6)

array([652.45104868, 592.97436783, 736.63680568, 770.34381451,
       632.64821722, 619.69442824])

In [48]:
#Q11.4: Shuffle the banking_data rows randomly
sd=bd.copy()
np.random.shuffle(sd)
print(sd)

[[    9 45000   560  1800    25]
 [   10 31000   430  1450    11]
 [    5 24000   430  1400    12]
 [    7 33000   470  1700    18]
 [    2 33000   460  1500    15]
 [    4 48000   520  1600    20]
 [    8 37000   430  1250    14]
 [    1 26000   310  1200    10]
 [    6 28000   340  1300     9]
 [    3 23000   350  1100     8]]


In [54]:
bd

array([[    1, 26000,   310,  1200,    10],
       [    2, 33000,   460,  1500,    15],
       [    3, 23000,   350,  1100,     8],
       [    4, 48000,   520,  1600,    20],
       [    5, 24000,   430,  1400,    12],
       [    6, 28000,   340,  1300,     9],
       [    7, 33000,   470,  1700,    18],
       [    8, 37000,   430,  1250,    14],
       [    9, 45000,   560,  1800,    25],
       [   10, 31000,   430,  1450,    11]])

In [56]:
# Q11.5: Set random seed to 123 and generate 4 random numbersdata
np.random.seed(123)
sr=np.random.random(4)
print(sr)

[0.69646919 0.28613933 0.22685145 0.55131477]


Linear Algebra Operations

In [59]:
#Q12.1: Calculate the dot product of account balance and credit score columns
s=np.dot(bd[:,1],bd[:,2])
print(s)

146040000


In [16]:
#Q12.2: Calculate the cross product of first two rows
np.cross(bd[0,:3],bd[1,:3])     #doubt

array([1730000,     160,  -19000])

In [19]:
bd

array([[    1, 26000,   310,  1200,    10],
       [    2, 33000,   460,  1500,    15],
       [    3, 23000,   350,  1100,     8],
       [    4, 48000,   520,  1600,    20],
       [    5, 24000,   430,  1400,    12],
       [    6, 28000,   340,  1300,     9],
       [    7, 33000,   470,  1700,    18],
       [    8, 37000,   430,  1250,    14],
       [    9, 45000,   560,  1800,    25],
       [   10, 31000,   430,  1450,    11]])

In [21]:
#Q12.3: Calculate the norm (magnitude) of the account balance column
s=np.linalg.norm(bd[:,1]) #doubt
print(s)

106780.14796768171


In [24]:
#Q12.4: Create a 3x3 matrix and calculate its determinant
import numpy as np
m=np.array([[4,5,6],[1,2,3],[7,8,9]])
s=np.linalg.det(m)
print(s)

9.51619735392994e-16


In [25]:
#Q12.5: Calculate the inverse of the 3x3 matrix
np.linalg.inv(m)

array([[-6.30503948e+15,  3.15251974e+15,  3.15251974e+15],
       [ 1.26100790e+16, -6.30503948e+15, -6.30503948e+15],
       [-6.30503948e+15,  3.15251974e+15,  3.15251974e+15]])

Question 13: String Operations

In [26]:
#Q13.1: Convert all customer IDs to strings
bd

array([[    1, 26000,   310,  1200,    10],
       [    2, 33000,   460,  1500,    15],
       [    3, 23000,   350,  1100,     8],
       [    4, 48000,   520,  1600,    20],
       [    5, 24000,   430,  1400,    12],
       [    6, 28000,   340,  1300,     9],
       [    7, 33000,   470,  1700,    18],
       [    8, 37000,   430,  1250,    14],
       [    9, 45000,   560,  1800,    25],
       [   10, 31000,   430,  1450,    11]])

In [28]:
s=bd[:,0].astype(str)
s

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

In [29]:
#Q13.2: Check if any customer ID contains '100'
n=np.char.find(s,'100')=0
n

SyntaxError: cannot assign to function call (2744000122.py, line 2)

In [31]:
#Q13.3: Convert all customer IDs to uppercase (if they were strings)
n=np.char.upper(s)
print(n)

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


In [32]:
# Q13.4: Count the length of each customer ID string
np.char.str_len(s)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 2])

In [33]:
#Q13.5: Replace '100' with 'CUST' in customer IDs
np.char.replace(s,"100","CUST")

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U2')

Date and Time Operations

In [37]:
#Q14.1: Convert years active to months
s=bd[:,4]*12
print(s)

[120 180  96 240 144 108 216 168 300 132]


In [38]:
# Q14.2: Calculate the average years active
np.mean(bd[:,4])

np.float64(14.2)

In [39]:
# Q14.3: Find customers who have been active for more than 15 years
bd[bd[:,4]>15]

array([[    4, 48000,   520,  1600,    20],
       [    7, 33000,   470,  1700,    18],
       [    9, 45000,   560,  1800,    25]])

In [40]:
# Q14.4: Calculate the total time all customers have been active (in years)
np.sum(bd[:,4])

np.int64(142)

In [48]:
# Q14.5: Find the customer with the shortest time active
n=bd[:,4]
s=np.argmin(n)
print("customer with short time:",s)

customer with short time: 2


In [49]:
bd

array([[    1, 26000,   310,  1200,    10],
       [    2, 33000,   460,  1500,    15],
       [    3, 23000,   350,  1100,     8],
       [    4, 48000,   520,  1600,    20],
       [    5, 24000,   430,  1400,    12],
       [    6, 28000,   340,  1300,     9],
       [    7, 33000,   470,  1700,    18],
       [    8, 37000,   430,  1250,    14],
       [    9, 45000,   560,  1800,    25],
       [   10, 31000,   430,  1450,    11]])


Advanced Array Operations

In [50]:
#Q15.1: Apply a function to calculate 5% interest on all account balances
bd[:,1]*0.05

array([1300., 1650., 1150., 2400., 1200., 1400., 1650., 1850., 2250.,
       1550.])

In [53]:
#Q15.2: Use np.where to categorize customers by balance ranges
s=bd[:,1]
c=np.where(s<20000,"low",
          np.where(s<45000,"medium","high"))
print(c)

['medium' 'medium' 'medium' 'high' 'medium' 'medium' 'medium' 'medium'
 'high' 'medium']


In [58]:
#Q15.3: Use np.select to categorize customers by credit score ranges
s=bd[:,2]
c=[(s<=350),
  (s<=450)&(s>=360),
  (s<=550)&(s>=460),
  (s<=650)]
co=["poor","fair","good","excellent"]
cat=np.select(c,co,default='nothing')
print(cat)

['poor' 'good' 'poor' 'good' 'fair' 'poor' 'good' 'fair' 'excellent'
 'fair']


In [56]:
bd

array([[    1, 26000,   310,  1200,    10],
       [    2, 33000,   460,  1500,    15],
       [    3, 23000,   350,  1100,     8],
       [    4, 48000,   520,  1600,    20],
       [    5, 24000,   430,  1400,    12],
       [    6, 28000,   340,  1300,     9],
       [    7, 33000,   470,  1700,    18],
       [    8, 37000,   430,  1250,    14],
       [    9, 45000,   560,  1800,    25],
       [   10, 31000,   430,  1450,    11]])

In [6]:
#Q15.4: Use np.piecewise to apply different interest rates based on balance
s=bd[:,1]
r=[0.01,0.02,0.03]
c=[s<=25000,(s>25000)&(s<=40000),(s>40000)]
Is=np.piecewise(s,c,r)
I=s*Is
print(I)

[0 0 0 0 0 0 0 0 0 0]


In [7]:
# Q15.5: Use np.apply_along_axis to calculate the sum of each row
s=np.apply_along_axis(np.sum,1,bd)
print(s)

[27521 34977 24461 50144 25847 29655 35195 38702 47394 32901]



Array Concatenation and Stacking

In [9]:
#Q16.1: Concatenate two arrays horizontally using np.hstack()
import numpy as np
s=np.array([[1,2],[3,4],[5,6]])
t=np.array([[11,12],[13,14],[15,16]])
r=np.hstack((s,t))
r

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16]])

In [10]:
#Q16.2: Concatenate two arrays vertically using np.vstack()
r=np.vstack((s,t))
r

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [11, 12],
       [13, 14],
       [15, 16]])

In [13]:
#Q16.3: Concatenate arrays along a specific axis using np.concatenate()
r=np.concatenate((s,t),1)
r

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16]])

In [14]:
#Q16.4: Stack arrays depth-wise using np.dstack()
np.dstack((s,t))

array([[[ 1, 11],
        [ 2, 12]],

       [[ 3, 13],
        [ 4, 14]],

       [[ 5, 15],
        [ 6, 16]]])

In [15]:
#Q16.5: Create a column stack using np.column_stack()
np.column_stack((s,t))

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16]])

Array Splitting Operations

In [16]:
#Q17.1: Split an array into 3 equal parts using np.split()
a=np.array([11,22,33,44,55,66,77,88,99])
np.split(a,3)

[array([11, 22, 33]), array([44, 55, 66]), array([77, 88, 99])]

In [19]:
#Q17.2: Split an array at specific indices using np.split()
np.split(a,[2,7])

[array([11, 22]), array([33, 44, 55, 66, 77]), array([88, 99])]

In [21]:
#Q17.3: Split an array horizontally using np.hsplit()
a= np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9,10,11,12]
])
np.hsplit(a,2)

[array([[1, 2, 3],
        [7, 8, 9]]),
 array([[ 4,  5,  6],
        [10, 11, 12]])]

In [24]:
#Q17.4: Split an array vertically using np.vsplit()
np.vsplit(a,2)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]

In [28]:
#Q17.5: Split an array into equal chunks using np.array_split()
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
parts = np.array_split(a, 2)
print(parts)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


Array Repetition and Tiling

In [29]:
# Repeat each element of an array 3 times using np.repeat()
np.repeat(a,3)

array([ 1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,  5,  6,  6,
        6,  7,  7,  7,  8,  8,  8,  9,  9,  9, 10, 10, 10])

In [31]:
#Q18.3: Repeat a 2D array using np.tile()
a=np.array([[1, 2],
           [3, 4]])
np.tile(a,(3,3))

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [33]:
#Q18.4: Create a pattern using np.tile()
import numpy as np
np.tile([0, 2], 4)

array([0, 2, 0, 2, 0, 2, 0, 2])

In [34]:
#Q18.5: Repeat elements with different counts using np.repeat()
a=np.array([1, 2, 3])
rep=np.array([1, 2, 3]) 
r=np.repeat(a, rep)
print(r)

[1 2 2 3 3 3]


In [35]:
#Q19.1: Compare two arrays for equality using np.array_equal()
a=np.array([1,2,3])
b=np.array([1,2,3])
c=np.array([2,3,4])
print(np.array_equal(a,b))
print(np.array_equal(a,c))

True
False


In [37]:
#Q19.2: Check if arrays are close using np.allclose()
a=np.array([1,2,3])
b=np.array([1,2,3])
print(np.allclose(a,b))

True


In [40]:
#Q19.3: Apply logical AND operation between arrays
a=np.array([0,2,3])
b=np.array([3,2,0])
print(np.logical_and(a,b))

[False  True False]


In [41]:
#Q19.4: Apply logical OR operation between arrays
a=np.array([1,0,0])
b=np.array([3,1,0])
print(np.logical_or(a,b))

[ True  True False]


In [42]:
#Q19.5: Apply logical NOT operation to an array
a=np.array([0,2,0])
b=np.array([2,0,3])
print(np.logical_not(a,b))

[1 0 1]


Array Set Operations

In [43]:
#Q20.1: Find unique elements in an array using np.unique()
a=np.array([11,3,3,31,4,6,13,4,7,9,7,7,5])
print(np.unique(a))

[ 3  4  5  6  7  9 11 13 31]


In [46]:
#Q20.2: Find the intersection of two arrays using np.intersect1d()
a=np.array([1,2,3,5,7,9,])
b=np.array([1,3,45,8,0,2,5])
print(np.intersect1d(a,b))

[1 2 3 5]


In [48]:
#Q20.3: Find the union of two arrays using np.union1d()
print(np.union1d(a,b))

[ 0  1  2  3  5  7  8  9 45]


In [50]:
#Q20.4: Find elements in first array but not in second using np.setdiff1d()
print(np.setdiff1d(a,b))

[7 9]


In [52]:
#Q20.5: Find the symmetric difference between two arrays using np.setxor1d()
print(np.setxor1d(a,b))

[ 0  7  8  9 45]
