In [1]:
import numpy as np

# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]
retail_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

print(retail_data)


[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [3]:
#What is the **total revenue** generated across all stores?
s=retail_data[:,1].sum()*retail_data[:,3].sum()
s

np.int64(4790500000)

In [10]:
#Which store recorded the **highest sales**?
retail_data[:,1].argmax()+1

np.int64(9)

In [11]:
#Which store recorded the **lowest sales**?
retail_data[:,1].argmin()+1

np.int64(1)

In [12]:
#What is the **average daily sales** per store?
retail_data[:,1].sum()/10

np.float64(33500.0)

In [13]:
#How many stores achieved sales **above ₹35,000**?
a=retail_data[:,1]
s=a[a>35000]
s

array([41000, 39000, 45000])

In [14]:
#6. Which store had the **highest customer footfall**?
retail_data[:,2].argmax()+1

np.int64(9)

In [15]:
#7. What is the **average number of customers** per store?
retail_data[:,2].sum()/10

np.float64(425.0)

In [19]:
#8. How many stores have **more than 450 customers**?
a=retail_data[:,2]
s=a[a>450]
s

array([500, 480, 550])

In [23]:
#9. Which store has the **lowest customer count**?
retail_data[:,2].argmin()+1

np.int64(1)

In [24]:
#10. Is there any store where **high sales do not correspond to high customers**?
s = retail_data[:,1].mean()
c = retail_data[:,2].mean()
m = retail_data[(retail_data[:,1] > s) & (retail_data[:,2] < c)]
m

array([[    5, 35000,   420,  1400,    12]])

In [25]:
#11. What is the **total inventory** across all stores?
retail_data[:,3].sum()

np.int64(14300)

In [26]:
#12. Which store has the **highest inventory stock**?
retail_data[:,3].argmax()+1

np.int64(9)

In [33]:
#13. How many stores have **inventory less than 1300 units**?
a=retail_data[:,3]
s=retail_data[a<1300]
s

array([[    1, 25000,   300,  1200,    10],
       [    3, 28000,   380,  1100,     8],
       [    8, 30000,   400,  1250,    14]])

In [29]:
#14. Which store has the **highest return rate** (returns ÷ inventory)?
s=(retail_data[:,4])/(retail_data[:,3])
s.argmax()+1


np.int64(9)

In [31]:
#15. Which stores have **returns greater than 15 units**?
s=retail_data[:,4]
a=retail_data[s>15]
a

array([[    4, 41000,   500,  1600,    20],
       [    7, 39000,   480,  1700,    18],
       [    9, 45000,   550,  1800,    25]])

In [37]:
#16. Is there a **positive correlation** between sales and customers?
s=retail_data[:,1]
t=retail_data[:,2]
c=np.corrcoef(s,t)[0,1]
c

np.float64(0.9593636912502479)

In [40]:
#17. Which store has **high customer visits but low sales**?
s = retail_data[:,2].mean()
t = retail_data[:,1].mean()
r = retail_data[(retail_data[:,2] > s) & (retail_data[:,1] < t)]
r

array([[    2, 32000,   450,  1500,    15]])

In [41]:
#18. Which store has **low customers but high sales**?
s = retail_data[:,1].mean()
t = retail_data[:,2].mean()
r = retail_data[(retail_data[:,1] > s) & (retail_data[:,2] < t)]
r

array([[    5, 35000,   420,  1400,    12]])

In [43]:
#19. How many stores have **sales per customer above ₹90**?
s=retail_data[:,1]/retail_data[:,2]
t=np.sum(s>90)
t

np.int64(0)

In [45]:
s=retail_data[:,1]/retail_data[:,2]
s

array([83.33333333, 71.11111111, 73.68421053, 82.        , 83.33333333,
       75.        , 81.25      , 75.        , 81.81818182, 80.48780488])

In [54]:
#20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?
s = retail_data[:,2].mean()
t = retail_data[:,3].mean()
r = (retail_data[(retail_data[:,1] < s) & (retail_data[:,2] >t)])
r

array([], shape=(0, 5), dtype=int64)

In [55]:
#21. If profit margin is **20% of sales**, what is the **profit per store**?
s=0.2 * retail_data[:,1]
s

array([5000., 6400., 5600., 8200., 7000., 5400., 7800., 6000., 9000.,
       6600.])

In [59]:
#22. Which store has the **highest profit**?
retail_data[:,4].argmax()+1

np.int64(9)

In [60]:
#23. Which store has the **lowest profit**?
retail_data[:,4].argmin()+1

np.int64(3)

In [62]:
#24. If sales increase by **10% next month**, what are the **new sales figures**?
s=0.1*retail_data[:,1]+retail_data[:,1]
s

array([27500., 35200., 30800., 45100., 38500., 29700., 42900., 33000.,
       49500., 36300.])

In [64]:
#25. How will **total profit** change with the 10% sales increase?
s=0.1*retail_data[:,4]+retail_data[:,4]
s

array([11. , 16.5,  8.8, 22. , 13.2,  9.9, 19.8, 15.4, 27.5, 12.1])

In [76]:
#26. Which stores need **inventory restocking** based on sales and current stock?
store_ids = retail_data[:, 0]
sales = retail_data[:, 1]
inventory = retail_data[:, 3]

# Define threshold: inventory should be at least 10% of sales
threshold = 0.1 * sales

# Find stores needing restock
restock_mask = inventory < threshold
stores_to_restock = store_ids[restock_mask]

print("Stores needing restocking:", stores_to_restock)

Stores needing restocking: [ 1  2  3  4  5  6  7  8  9 10]


In [77]:
#27. Which stores show **high returns percentage** and might require **quality checks**?
store_ids = retail_data[:, 0]
sales = retail_data[:, 1]
returns = retail_data[:, 4]

# Calculate returns percentage
returns_percentage = (returns / sales) * 100

# Define threshold (e.g., >0.05%)
threshold = 0.05
quality_check_mask = returns_percentage > threshold

# Stores needing quality check
stores_quality_check = store_ids[quality_check_mask]
print("Stores needing quality checks:", stores_quality_check)
print("Return percentages:", returns_percentage[quality_check_mask])

Stores needing quality checks: [9]
Return percentages: [0.05555556]


In [72]:
#28. Which store is the **best performer overall** (sales, customers, inventory turnover)?
store_ids = retail_data[:, 0]
sales = retail_data[:, 1]
customers = retail_data[:, 2]
inventory = retail_data[:, 3]

# Inventory turnover
inv_turnover = sales / inventory

# Normalize each metric (min-max scaling)
sales_norm = (sales - sales.min()) / (sales.max() - sales.min())
customers_norm = (customers - customers.min()) / (customers.max() - customers.min())
inv_turnover_norm = (inv_turnover - inv_turnover.min()) / (inv_turnover.max() - inv_turnover.min())

# Weighted score (equal weight for simplicity)
score = (sales_norm + customers_norm + inv_turnover_norm) / 3

# Find best performer
best_store = store_ids[np.argmax(score)]

print("Best performing store overall:", int(best_store))

Best performing store overall: 9


In [73]:
#29. Which store is the **worst performer overall**?
store_ids = retail_data[:, 0]
sales = retail_data[:, 1]
customers = retail_data[:, 2]
inventory = retail_data[:, 3]

# Inventory turnover
inv_turnover = sales / inventory

# Normalize each metric (min-max scaling)
sales_norm = (sales - sales.min()) / (sales.max() - sales.min())
customers_norm = (customers - customers.min()) / (customers.max() - customers.min())
inv_turnover_norm = (inv_turnover - inv_turnover.min()) / (inv_turnover.max() - inv_turnover.min())

# Weighted score (equal weight for simplicity)
score = (sales_norm + customers_norm + inv_turnover_norm) / 3
worst_store = store_ids[np.argmin(score)]

print("Worst performing store overall:", int(worst_store))

Worst performing store overall: 1


In [75]:
#30. Which stores can be considered for **expansion** based on strong sales and customer metrics?
store_ids = retail_data[:, 0]
sales = retail_data[:, 1]
customers = retail_data[:, 2]

# Normalize
sales_norm = (sales - sales.min()) / (sales.max() - sales.min())
customers_norm = (customers - customers.min()) / (customers.max() - customers.min())

# Combined score for expansion (equal weights)
expansion_score = (sales_norm + customers_norm) / 2

# Select top stores (e.g., top 3)
top_expansion_indices = np.argsort(expansion_score)[-3:][::-1]
stores_for_expansion = store_ids[top_expansion_indices]

print("Stores recommended for expansion:", stores_for_expansion)

Stores recommended for expansion: [9 4 7]
